# Generated by Django 5.0.9 on 2024-10-17 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bb_announce', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcecat',
            name='title',
            field=models.CharField(choices=[('TK', 'Танки'), ('HL', 'Хилы'), ('DD', 'ДД'), ('ME', 'Торговцы'), ('GM', 'Гилдмастеры'), ('QG', 'Квестгиверы'), ('BM', 'Кузнецы'), ('TN', 'Кожевники'), ('PO', 'Зельевары'), ('SC', 'Мастера заклинаний')], default='TK', max_length=20, unique=True),
        ),
    ]
