# Generated by Django 5.0.9 on 2024-10-17 13:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bb_announce', '0002_alter_announcecat_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='announce_cat',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bb_announce.announcecat'),
        ),
    ]
