# Generated by Django 5.0.9 on 2024-10-17 14:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bb_announce', '0003_alter_announcement_announce_cat'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='announce_cat',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Announce_AnnounceCat_feedback', to='bb_announce.announcecat'),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='title',
            field=models.CharField(max_length=170),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Announce_User_feedback', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='replyannounce',
            name='announce',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='Reply_Announce_feedback', to='bb_announce.announcement'),
        ),
        migrations.AlterField(
            model_name='replyannounce',
            name='text',
            field=models.TextField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='replyannounce',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Reply_User_feedback', to=settings.AUTH_USER_MODEL),
        ),
    ]
